### PR TITLE
Add product & product list layouts

### LINKED ISSUE #147: Add “Product” and “Product list” layouts.
PR #148

### PR DESCRIPTION
**Pull request by siimha**
Related: Edicy/operations#241
Closes: #147 
## Some guides for testing:
- [x]  Check if bgpicker, image drop area and page/article image saving works properly in the following layouts:
  - [x]  **Product list**
  - [x]  **Product**
- [x] Check if **Product list** layout works properly everywhere.
- [x] Check if **Product** layout works properly everywhere.
- [x] Check if **Blog & news** layout didn't broke down.
- [x] Check if **Product list** layout works up to second level in menu.
- [x] Check if **Product list** works for _root item_ (first page).
- [x] Check if **Product** works for _root item_ **(first page)**.
- [x] Check if main menu in desktop didn't broke down.
- [x] Check if main menu in mobile didn't broke down.
- [x] Do a small check for all other layouts to see if something got broken.
- [x] If **first page** is used as **Product list**, there's an option to hide _product_ related pages from main menu. Check if that works as intended.

***

## After release of the template

- [ ] Notify sirelboutique.com owner about the product list templates – https://voog.freshdesk.com/helpdesk/tickets/23555
- [ ] Switch sirelboutique.com back to standard template or update the code manually to provide the client the templates

### CODE REVIEW

**Comment by siimha** [comment]
* [ ] Add CDN for lazyload

**Comment by SSirjes** [comment]
**_Product layout:_**
* [ ] product title should distinct from body text.

_Maybe something like this:_
screen_shot_2018-03-06_at_13_42_29

**Comment by SSirjes** [comment]
* [ ] If front page layout is 'Product list', then 'Settings' button seem's not working.
Default, product items should not visible in main menu.

**Comment by siimha** [comment]
* [ ]Change edy-img-drop-area-placeholder color to var(--color-secondary)
* [ ] Change buy button color &  boarder color (also hower) to var(--color-primary)
* [ ] Change product image background-color to transparent

**Comment by SSirjes** [comment]
**Product list**

* [ ] Preview mode don't display product title

screen shot 2018-03-12 at 16 53 46

**Comment by SSirjes** [comment]
* [ ] Look breadcrumbs menu font-size

**Comment by SSirjes** [comment]
* [ ] Breadcrumbs menu > menu-separator should have same font-size as breadcrumbs menu item

screen shot 2018-03-13 at 15 44 59

**Comment by siimha** [comment]
* [ ] <h1>{{ page.title }}</h1> size should change from design editor

**Comment by SSirjes** [comment]
* [ ] If I change front page layout to 'Product list', then default is content are 'Gallery'

screen shot 2018-03-15 at 11 16 23

**Comment by siimha** [comment]
* [ ] Remove empty classes

**Comment by SSirjes** [comment]
Front page

* [ ] text area and product block needs more whitespace between each other

screen shot 2018-03-20 at 14 20 26

**Comment by SSirjes** [comment]
* [ ] default is content text font-size 19px.
On product layout it's only 14px.

screen shot 2018-03-20 at 15 48 01

**Comment by siimha** [comment]
* [ ] Change item title & link to h3

**Comment by SSirjes** [comment]
* [ ] If product image is cropped, then background-color is too dark.
It should be: 
```
.with-image .item-top .top-inner {
    background-color: rgba(0,0,0,.05);
}
```

**Comment by siimha** [comment]
* [ ] If parent page of the "Product" or "Product list" pages is hidden, the children are not listed as products/categories & not displayed. Also breadcumbs are missing & you cant add subpages to visible children if parent page of the "Product" or "Product list" pages is hidden.

**Comment by SSirjes** [comment]
* [ ] if product has variants, then long variant name and select aroow overlap each other

screen_shot_2018-04-25_at_15_49_01

**Comment by siimha** [comment]
On page loading all possible breadcrumbs are rendered for all product list:
* [ ] Render only selected item breadcrumbs

Fix for menu-breadcrumbs-items-loop:
`{% for i in (1..5) %}
  {% assign level_str = 'menuitems_with_hidden_on_level_' | append: i %}
    {% for item in site[level_str] %}
      {% if item.selected? %}
      <span class="menu-separator">/</span>
      {% menulink item wrapper-tag="li" wrapper-class="menu-item" %}
     {% endif %}
   {% endfor %}
{% endfor %}`

**Pull request merged**
